version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/code
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container_application
    ports:
      - "80:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: /swagger/openapi.yaml
  rabbitmq: 
    image: rabbitmq:3.13-rc-management-alpine
    container_name: rabbitmq_container
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "postech"
      RABBITMQ_DEFAULT_PASS: "soat"
volumes:
  mongodb: